# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-27 15:29
from __future__ import unicode_literals

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move_out',
            name='destiny',
            field=models.CharField(default='Almacen', max_length=30),
        ),
        migrations.AlterField(
            model_name='move_out',
            name='origin',
            field=models.CharField(default='Almacen', max_length=30),
        ),
        migrations.AlterField(
            model_name='movein',
            name='destiny',
            field=models.CharField(default='Almacen', max_length=30),
        ),
        migrations.AlterField(
            model_name='moveout',
            name='origin',
            field=models.CharField(default='Almacen', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.CharField(default='Almacen', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(default='Puerto La Cruz', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(default='Venezuela', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='enterprise',
            field=models.CharField(default='Grupo Alcars', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
