# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-20 22:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given', models.IntegerField()),
                ('received', models.IntegerField()),
                ('reason', models.TextField(max_length=64)),
                ('product_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.ProductClass')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField(unique=True)),
                ('name', models.TextField(max_length=128)),
                ('last_name', models.TextField(max_length=128)),
                ('cedula', models.IntegerField(unique=True)),
                ('gender', models.TextField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otros')], default='M')),
                ('birthdate', models.DateField()),
                ('address', models.TextField(max_length=256)),
                ('civil_status', models.TextField(choices=[('S', 'Soltero'), ('C', 'Casado'), ('V', 'Viudo')], default='S')),
                ('home_phone', models.TextField(max_length=40)),
                ('mobile_phone', models.TextField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rrhh.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=128)),
                ('salary', models.FloatField()),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('pay_range', models.TextField(choices=[('S', 'Semanal'), ('Q', 'Quincenal')], default='S')),
                ('shift', models.TextField(choices=[('D', 'Diurno'), ('N', 'Nocturno'), ('M', 'Mixto')], default='D')),
                ('employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rrhh.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Spawn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=128)),
                ('last_name', models.TextField(max_length=128)),
                ('gender', models.TextField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otros')], default='F')),
                ('birthdate', models.DateField()),
                ('employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rrhh.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Spouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=128)),
                ('last_name', models.TextField(max_length=128)),
                ('gender', models.TextField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otros')], default='F')),
                ('birthdate', models.DateField()),
                ('mobile_phone', models.TextField(max_length=40)),
                ('employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rrhh.Employee')),
            ],
        ),
    ]
