# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-20 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='reason',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='employee',
            name='civil_status',
            field=models.CharField(choices=[('S', 'Soltero'), ('C', 'Casado'), ('V', 'Viudo')], default='S', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otros')], default='M', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='home_phone',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile_phone',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='position',
            name='pay_range',
            field=models.CharField(choices=[('S', 'Semanal'), ('Q', 'Quincenal')], default='S', max_length=20),
        ),
        migrations.AlterField(
            model_name='position',
            name='shift',
            field=models.CharField(choices=[('D', 'Diurno'), ('N', 'Nocturno'), ('M', 'Mixto')], default='D', max_length=20),
        ),
        migrations.AlterField(
            model_name='spawn',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otros')], default='F', max_length=20),
        ),
        migrations.AlterField(
            model_name='spawn',
            name='last_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='spawn',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='spouse',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otros')], default='F', max_length=20),
        ),
        migrations.AlterField(
            model_name='spouse',
            name='last_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='spouse',
            name='mobile_phone',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='spouse',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
