# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-20 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0002_auto_20171220_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birthdate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='spawn',
            name='birthdate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='spouse',
            name='birthdate',
            field=models.DateTimeField(),
        ),
    ]
