# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-27 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0004_auto_20171220_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250)),
                ('type', models.CharField(default='', help_text='Talla, Color o Descripcion', max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='control',
            name='product_class',
        ),
        migrations.RemoveField(
            model_name='employeecontrol',
            name='date',
        ),
        migrations.RemoveField(
            model_name='position',
            name='salary',
        ),
        migrations.AddField(
            model_name='employeecontrol',
            name='type',
            field=models.CharField(choices=[('I', 'Agregar'), ('O', 'Quitar')], default='I', max_length=20),
        ),
        migrations.AddField(
            model_name='position',
            name='base_salary',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='position',
            name='food_salary',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='spouse',
            name='cedula',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='spawn',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rrhh.Employee'),
        ),
        migrations.DeleteModel(
            name='Control',
        ),
        migrations.AddField(
            model_name='employeecontrol',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rrhh.Product'),
        ),
    ]
