# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-27 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0005_auto_20181027_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecontrol',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
