# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-28 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0007_employeecontrol_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecontrol',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.ProductClass'),
        ),
    ]
