# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-29 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0008_auto_20181028_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='fecha_de_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='salario',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
