# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-01 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0009_auto_20181029_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='spawn',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='spouse',
            name='employee',
        ),
        migrations.AlterField(
            model_name='employee',
            name='fecha_de_ingreso',
            field=models.DateField(blank=True, default='1994-11-24', null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salario',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.DeleteModel(
            name='Spawn',
        ),
        migrations.DeleteModel(
            name='Spouse',
        ),
    ]
