# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-01 08:34
from __future__ import unicode_literals

from django.db import migrations, models
from django.db import migrations
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250)),
                ('type', models.CharField(default='', help_text='Talla, Color o Descripcion', max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='employeecontrol',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeecontrol',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='employeecontrol',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.ProductClass'),
        ),
    ]
