# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-06 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0011_auto_20181106_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='fao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='ivss',
            field=models.BooleanField(default=False),
        ),
    ]
