# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-06 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0012_auto_20181106_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='home_phone',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
